<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Document</title>
	<link rel="stylesheet" href="<?= $wwwUrl ?>/css/generationy.css">
	<script src="http://code.jquery.com/jquery-2.1.4.min.js"></script>
</head>
<body>
	<article id='hide' class="hidde">
		<section id='score'>
		</section>

		<button type='submit' id='reload'>ressayer</button>
		
	</article>
	


	<canvas id='moncanvas' width=600 height="600">
	</canvas>


<h1> tableau des meilleurs scoore</h1>
		<?php for ( $j = 0; $j < 5; $j++ ) {?>
		<p> <?=$j+1?>: <?=$best[$j]['FirstName'] ?> score <?= $best[$j] ['Score']?></p>
	    <?php }?>


     


</body>
</html>