<h2><i class="fa fa-user"></i> Création d'un compte joueur</h2>

<form class="generic-form" action="<?= $requestUrl ?>/user/register" method="POST">


	<fieldset>
		<legend><i class="fa fa-book"></i> Identité </legend>
		<ul>
			<li>
				<label for="lastName">Nom :</label>
				<input id="lastName" type="text" name="lastName" data-required data-name="Nom" value="">
			
			</li>
			<li>
				<label for="firstName">Prénom :</label>
				<input id="firstName" type="text" name="firstName" data-required data-name="Prénom" value="">
			</li>
		
		</ul>
	</fieldset>

	<fieldset>
		<legend><i class="fa fa-lock"></i> Informations d'authentification</legend>
		<ul>
	        <li>
	            <label for="email">E-mail :</label>
	            <input id="email" type="text" name="email" data-required data-name="E-mail" value="">
	        </li>
	        <li>
	            <label for="password">Mot de passe :</label>
	            <input id="password" type="password" name="password" data-required data-name="Mot de passe" data-length="8">
	        </li>
		</ul>
	</fieldset>

	<ul>
		<li>
			<input class="button button-primary" type="submit" value="Créer le compte">
			<a class="button button-cancel small" href="<?= $requestUrl ?>">Annuler</a>
		</li>
	</ul>
</form>